<template>
  <v-content>
    <v-container
      class="fill-height"
      fluid
    >
      <v-row
        align="center"
        justify="center"
      >
        <v-col
          cols="12"
          lg="6"
          sm="8"
          md="8"
        >
          <login-signInForm></login-signInForm>
        </v-col>
      </v-row>
    </v-container> 
  </v-content>
</template>
<script>
export default {
  data() {
  }
};
</script>
<style>
</style>